# Generated by Django 5.2.7 on 2025-10-24 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('S', 'Vendedor'), ('C', 'Servicio a clientes'), ('M', 'Gerente'), ('A', 'Administrador')], default='S', max_length=1, verbose_name='rol')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono oficina')),
                ('cel_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono celular')),
                ('position', models.CharField(max_length=30, verbose_name='Puesto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
