# Generated by Django 5.2.7 on 2025-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('S', 'Vendedor'), ('C', 'Servicio a clientes'), ('M', 'Gerente'), ('A', 'Administrador')], default='S', max_length=1, verbose_name='Rol'),
        ),
    ]
