# Generated by Django 5.2.7 on 2025-10-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
