# Generated by Django 5.2.7 on 2025-10-28 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="La extensión debe ser de 1 a 5 dígitos. No puede ser 0's", regex='^(?!0+$)(?:\\d{1,5})?$')], verbose_name='Extensión'),
        ),
    ]
