# Generated by Django 5.2.7 on 2025-10-25 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono oficina')),
                ('phone_extension', models.CharField(blank=True, max_length=6, null=True, verbose_name='Extensión')),
                ('cel_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono celular')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cliente')),
                ('slug', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC no tiene un formato válido', regex='^([A-Za-zÑñ\\x26]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1]))([A-Za-z\\d]{3})?$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
