# Generated by Django 5.2.7 on 2025-10-28 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC no tiene un formato válido', regex='^([A-Za-zÑñ\\x26]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1]))([A-Za-z\\d]{3})?$')]),
        ),
    ]
