# Generated by Django 5.2.7 on 2025-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_contact_created_by_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Puesto'),
        ),
    ]
