# Generated by Django 5.2.7 on 2025-11-11 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cel_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono oficina'),
        ),
    ]
