# Generated by Django 5.2.7 on 2025-10-28 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_rfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(max_length=19, unique=True, verbose_name='Cotización')),
                ('status', models.CharField(choices=[('DFT', 'Vendedor'), ('RVW', 'Aprobación pendiente'), ('APP', 'Aprobada'), ('SNT', 'Enviada'), ('WON', 'Ganada'), ('LST', 'Perdida'), ('EXP', 'Expirada')], default='DFT', max_length=3, verbose_name='Estatus')),
                ('payment_terms', models.CharField(choices=[('CSH', 'Contado'), ('N07', 'Crédito 7 días'), ('N15', 'Crédito 15 días'), ('N30', 'Crédito 30 días'), ('N60', 'Crédito 60 días'), ('N90', 'Crédito 90 días')], default='CSH', max_length=3, verbose_name='términos de pago')),
                ('valid_until', models.DateField(verbose_name='Válida hasta')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_quotes', to='customers.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_uotes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
