# Generated by Django 5.2.7 on 2025-10-29 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_contact_created_by_alter_contact_first_name_and_more'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_quotes', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(choices=[('CSH', 'Contado'), ('N07', 'Crédito 7 días'), ('N15', 'Crédito 15 días'), ('N30', 'Crédito 30 días'), ('N60', 'Crédito 60 días'), ('N90', 'Crédito 90 días')], default='CSH', max_length=3, verbose_name='Términos de pago'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
