# Generated by Django 5.2.7 on 2025-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_is_active_alter_quote_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='Cotización'),
        ),
    ]
