# Generated by Django 5.2.7 on 2025-11-03 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_created_by_alter_category_updated_by_and_more'),
        ('customers', '0007_alter_contact_created_by_alter_contact_first_name_and_more'),
        ('quotes', '0006_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('discount', models.PositiveSmallIntegerField(choices=[(0, '0%'), (3, '3%'), (5, '5%'), (7, '7%'), (10, '10%'), (15, '15%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Descuento')),
                ('delivery_time', models.PositiveSmallIntegerField(default=0, help_text='Tiempo en días hábiles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de entrega')),
            ],
            options={
                'verbose_name': 'Línea de cotización',
                'verbose_name_plural': 'Líneas de cotización',
                'ordering': ['section_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Sección de cotización',
                'verbose_name_plural': 'Secciones de cotización',
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AddField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de perdida'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lost_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Perdida por'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reazón de pérdida'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por'),
        ),
        migrations.AddField(
            model_name='quote',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='quote',
            name='won_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Ganada por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'created'], name='quotes_quot_status_39c5e6_idx'),
        ),
        migrations.AddField(
            model_name='quotecomment',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quotecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_quoted_lines', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quotesection',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_sections', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_lines', to='quotes.quotesection'),
        ),
        migrations.AddIndex(
            model_name='quotecomment',
            index=models.Index(fields=['user'], name='quotes_quot_user_id_b30eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='quotecomment',
            index=models.Index(fields=['quote'], name='quotes_quot_quote_i_cf8017_idx'),
        ),
        migrations.AddIndex(
            model_name='quotecomment',
            index=models.Index(fields=['quote', 'created'], name='quotes_quot_quote_i_8e45e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotesection',
            index=models.Index(fields=['name'], name='quotes_quot_name_60bf62_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotesection',
            constraint=models.UniqueConstraint(fields=('name', 'quote'), name='unique_section_per_quote'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['quote'], name='quotes_quot_quote_i_9dbd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['section'], name='quotes_quot_section_cc78c2_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['product'], name='quotes_quot_product_a416d4_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['discount'], name='quotes_quot_discoun_a5261a_idx'),
        ),
    ]
