# Generated by Django 5.2.7 on 2025-10-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
