# Generated by Django 5.2.8 on 2025-11-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relatedproduct',
            name='product-related-unique',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.UniqueConstraint(fields=('product', 'related_product'), name='product_related_unique'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('related_product')), _negated=True), name='related_product_not_self'),
        ),
    ]
