# Generated by Django 5.2.7 on 2025-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_relatedproduct_options_relatedproduct_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_editable',
            field=models.BooleanField(default=False, verbose_name='Precio editable'),
        ),
    ]
