# Generated by Django 5.2.7 on 2025-10-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_created_by_alter_quote_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DFT', 'Borrador'), ('RVW', 'Aprobación pendiente'), ('APP', 'Aprobada'), ('SNT', 'Enviada'), ('WON', 'Ganada'), ('LST', 'Perdida'), ('EXP', 'Expirada')], default='DFT', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válida hasta'),
        ),
    ]
