# Generated by Django 5.2.7 on 2025-10-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_quote_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
