# Generated by Django 5.2.7 on 2025-11-04 15:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_created_by_alter_category_updated_by_and_more'),
        ('customers', '0007_alter_contact_created_by_alter_contact_first_name_and_more'),
        ('quotes', '0007_quotecomment_quoteline_quotesection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pérdida'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón de pérdida'),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_quoted_lines', to='catalog.product', verbose_name='Número de parte'),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_lines', to='quotes.quotesection', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='quotesection',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Sección'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'created'], name='quotes_quot_user_id_ffdf00_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['is_active'], name='quotes_quot_is_acti_a49d56_idx'),
        ),
    ]
