# Generated by Django 5.2.8 on 2025-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quote_lost_at_alter_quote_lost_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesection',
            name='type',
            field=models.CharField(default='', max_length=3, verbose_name='Tipo de sección'),
        ),
    ]
