# Generated by Django 5.2.8 on 2025-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quotesection_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotesection',
            old_name='type',
            new_name='section_type',
        ),
    ]
