# Generated by Django 5.2.8 on 2025-11-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_rename_type_quotesection_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesection',
            name='sub_total',
        ),
    ]
