# Generated by Django 5.2.8 on 2025-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_remove_quotesection_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesection',
            name='section_type',
            field=models.CharField(choices=[('EQU', 'Equipo'), ('CON', 'Consumible'), ('SER', 'Servicio'), ('ACC', 'Accesorio'), ('REF', 'Refacciones')], max_length=3, verbose_name='Tipo de sección'),
        ),
    ]
