# Generated by Django 5.2.8 on 2025-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_quotesection_section_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotesection',
            name='unique_section_per_quote',
        ),
        migrations.AddConstraint(
            model_name='quotesection',
            constraint=models.UniqueConstraint(fields=('quote', 'section_type'), name='unique_section_type_per_quote'),
        ),
    ]
