# Generated by Django 5.2.8 on 2025-11-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_remove_quotesection_unique_section_per_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='discount_total',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='total',
        ),
    ]
