# Generated by Django 5.2.8 on 2025-11-27 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_remove_quote_discount_total_remove_quote_sub_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='lost_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Perdida por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Ganada por'),
        ),
    ]
